In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
import glob
path = 'datasets/'
list_folder = ['balita','bayi','hamil','kekerasan','faskes','umum']
all_tables = {}

for folder in list_folder:
    all_zip = []
    all_zip = glob.glob(path + folder + '/' + '*.zip')
    all_tables[folder] = all_zip

In [9]:
from zipfile import ZipFile

for folder in list_folder:
    for file_name in all_tables[folder]:
        with ZipFile(file_name, 'r') as zip:
            # printing all the contents of the zip file
            csv_file = zip.namelist()[0]
            pathway = (path + folder)

            # extracting all the files
            zip.extract(csv_file,pathway)

In [11]:
import glob
import re
import os
pathway = 'datasets/umum/data.jabarprov.go.id/'

def dinkes(file_path):
    all_files = glob.glob(file_path + '*.csv')
    list_files = [pd.read_csv(filename,index_col=None, header=0).copy() for filename in all_files]

    col_to_delete = ['kode_provinsi','nama_provinsi','id','kode_kabupaten_kota','satuan']
    done_list = []
    
    file_name = [re.search(r"(?<=od\_)(\S+)(?=\.csv)",file).group() for file in all_files]
    save_path = re.search(r"(\S+)(?=data.jabarprov.go.id)",pathway).group()

    for num,files in enumerate(list_files):
        for col in files.columns:
            if files[col].isna().any()==False:
                if re.match(r"persen", col):
                    files[col].astype('float64')
                elif re.match(r"jumlah", col):
                    files[col].astype('int64')
            
            if col in col_to_delete:
                files.drop(columns=col,inplace=True)
            
            
        files.to_csv(os.path.join(save_path, file_name[num] + '.csv'))

In [12]:

dinkes(pathway)

In [ ]:
pathway = 'datasets/umum/data.jabarprov.go.id/'
indeks_pembangunan_manusia = pd.read_csv(pathway + 'bps-od_15042_indeks_pmbngnn_manusia__prov_di_indonesia_data.csv',index_col=None, header=0).copy()

col_to_delete = ['kode_provinsi',
                    'bps_kode_kabupaten_kota',
                    'bps_kode_kecamatan',
                    'bps_nama_kecamatan',
                    'bps_kode_desa_kelurahan',
                    'bps_nama_desa_kelurahan',
                    'kemendagri_kode_kecamatan',
                    'kemendagri_nama_kecamatan',
                    'kemendagri_kode_desa_kelurahan',
                    'kemendagri_nama_desa_kelurahan',
                    'id','kode_kabupaten_kota','satuan']

for col in rumah_singgah.columns:           
    if col in col_to_delete:
        rumah_singgah.drop(columns=col,inplace=True)
    if col == 'bps_nama_kabupaten_kota':
        rumah_singgah.rename(columns={'bps_nama_kabupaten_kota':'nama_kabupaten_kota'},inplace=True)
            
# pd.to_datetime(rumah_singgah['tahun'])
# generate binary values using get_dummies
rumah_singgah_ibu_hamil = pd.get_dummies(rumah_singgah, columns=["ketersediaan_rumah_singgah_tunggu"], prefix=['jumlah_rumah_singgah_tiap_desa'])
# rumah_singgah_ibu_hamil['tahun']=pd.to_datetime(rumah_singgah_ibu_hamil['tahun'], format='%Y')

rumah_singgah_ibu_hamil = rumah_singgah_ibu_hamil.groupby(['nama_kabupaten_kota','tahun']).sum().reset_index()
rumah_singgah_ibu_hamil.iloc[:,1:] = rumah_singgah_ibu_hamil.iloc[:,1:].astype('int64')
rumah_singgah_ibu_hamil.rename(columns={'jumlah_rumah_singgah_tiap_desa_ADA':'jumlah_desa_dengan_rumah_singgah',
                                        'jumlah_rumah_singgah_tiap_desa_TIDAK ADA':'jumlah_desa_tanpa_rumah_singgah'},inplace=True)

rumah_singgah_ibu_hamil.to_csv(os.path.join('datasets/hamil/', 'sedia_rumah_singgah_rumah_tunggu_untuk_ibu_hamil.csv'))

rumah_singgah_ibu_hamil

In [13]:
pathway = 'datasets/umum/data.jabarprov.go.id/'
indeks_pembangunan_manusia = pd.read_csv(pathway + 'bps-od_15042_indeks_pmbngnn_manusia__prov_di_indonesia_data.csv',index_col=None, header=0).copy()

col_to_delete = ['kode_provinsi','id','satuan']

for col in indeks_pembangunan_manusia.columns:           
    if col in col_to_delete:
        indeks_pembangunan_manusia.drop(columns=col,inplace=True)
    if col == 'bps_nama_kabupaten_kota':
        indeks_pembangunan_manusia.rename(columns={'bps_nama_kabupaten_kota':'nama_kabupaten_kota'},inplace=True)


indeks_pembangunan_manusia['tahun']=indeks_pembangunan_manusia['tahun'].astype('int64')

indeks_pembangunan_manusia.to_csv(os.path.join('datasets/umum/', '15042_indeks_pmbngnn_manusia__prov_di_indonesia_data.csv'))
indeks_pembangunan_manusia

      nama_provinsi  indeks_pembangunan_manusia  tahun
0              ACEH                       67.09   2010
1    SUMATERA UTARA                       67.09   2010
2    SUMATERA BARAT                       67.25   2010
3              RIAU                       68.65   2010
4             JAMBI                       65.39   2010
..              ...                         ...    ...
369  SULAWESI BARAT                       66.11   2020
370          MALUKU                       69.49   2020
371    MALUKU UTARA                       68.49   2020
372     PAPUA BARAT                       65.09   2020
373           PAPUA                       60.44   2020

[374 rows x 3 columns]

## data cleaning

In [14]:
pathway = 'datasets/umum/'

In [15]:
cleaned_dict={}

In [17]:
cleaned_dict['indeks_pembangunan_manusia_provinsi'] = indeks_pembangunan_manusia

In [28]:
pathway = 'datasets/umum/'
indeks_kemiskinan_2018 = pd.read_csv('datasets/umum/17111_indeks_keparahan_kemiskinan_berdasarkan_kabupatenkota_data.csv').copy()
indeks_kemiskinan_2018['tahun'] = indeks_kemiskinan_2018['tahun'].astype('int64')
indeks_kemiskinan_2018.drop(columns='Unnamed: 0',inplace=True)


indeks_kedalaman = pd.read_csv('datasets/umum/18026_indeks_kedalaman_kemiskinan_berdasarkan_kabupatenkota_data.csv').copy()
indeks_kedalaman['tahun'] = indeks_kedalaman['tahun'].astype('int64')
indeks_kedalaman.drop(columns='Unnamed: 0',inplace=True)

indeks_kemiskinan_2018 = indeks_kemiskinan_2018.merge(indeks_kedalaman, on=['nama_kabupaten_kota','tahun'])

persentase_miskin = pd.read_csv('datasets/umum/persentase_penduduk_miskin_berdasarkan_kabupatenkota_data.csv').copy()
persentase_miskin['tahun'] = persentase_miskin['tahun'].astype('int64')
persentase_miskin.drop(columns='Unnamed: 0',inplace=True)

indeks_kemiskinan_2018 = indeks_kemiskinan_2018.merge(persentase_miskin, on=['nama_kabupaten_kota','tahun'])
indeks_kemiskinan_2018 = indeks_kemiskinan_2018.rename(columns={'persentase_penduduk':'persentase_penduduk_miskin'})
indeks_kemiskinan_2018

,nama_kabupaten_kota,indeks_keparahan_kemiskinan,tahun,indeks_kedalaman_kemiskinan,persentase_penduduk_miskin
0,KABUPATEN BOGOR,0.26,2018,1.12,7.14
1,KABUPATEN SUKABUMI,0.19,2018,0.86,6.76
2,KABUPATEN CIANJUR,0.27,2018,1.34,9.81
3,KABUPATEN BANDUNG,0.20,2018,0.87,6.65
4,KABUPATEN GARUT,0.37,2018,1.49,9.27
...,...,...,...,...,...
76,KOTA BEKASI,0.15,2020,0.60,4.38
77,KOTA DEPOK,0.06,2020,0.29,2.45
78,KOTA CIMAHI,0.18,2020,0.75,5.11
79,KOTA TASIKMALAYA,0.39,2020,1.75,12.97
80,KOTA BANJAR,0.12,2020,0.70,6.09

In [29]:
cleaned_dict['indeks_kemiskinan_2018'] = indeks_kemiskinan_2018

In [34]:
indeks_kesehatan_2010 = pd.read_csv('datasets/umum/17517_indeks_kesehatan_berdasarkan_kabupatenkota_data.csv').copy()
indeks_kesehatan_2010['tahun'] = indeks_kesehatan_2010['tahun'].astype('int64')
indeks_kesehatan_2010.drop(columns='Unnamed: 0',inplace=True)

indeks_pembangunan_manusia_2010 = pd.read_csv('datasets/umum/indeks_pembangunan_manusia_berdasarkan_kabupatenkota_data.csv').copy()
indeks_pembangunan_manusia_2010['tahun'] = indeks_pembangunan_manusia_2010['tahun'].astype('int64')
indeks_pembangunan_manusia_2010.drop(columns='Unnamed: 0',inplace=True)

indeks_kesehatan_2010 = indeks_kesehatan_2010.merge(indeks_pembangunan_manusia_2010, how='outer', on=['nama_kabupaten_kota','tahun'])
indeks_kesehatan_2010 = indeks_kesehatan_2010.merge(persentase_miskin, how='outer', on=['nama_kabupaten_kota','tahun'])
indeks_kesehatan_2010 = indeks_kesehatan_2010.rename(columns={'persentase_penduduk':'persentase_penduduk_miskin'})
cleaned_dict['indeks_kesehatan_2010'] = indeks_kesehatan_2010

indeks_kesehatan_2010

,nama_kabupaten_kota,indeks_kesehatan,tahun,indeks_pembangunan_manusia,persentase_penduduk_miskin
0,KABUPATEN BOGOR,77.43,2010,64.35,9.97
1,KABUPATEN SUKABUMI,76.10,2010,60.69,10.65
2,KABUPATEN CIANJUR,75.02,2010,58.58,14.32
3,KABUPATEN BANDUNG,81.44,2010,67.28,9.30
4,KABUPATEN GARUT,77.44,2010,60.23,13.94
...,...,...,...,...,...
320,KOTA DEPOK,84.03,2021,NaN,NaN
321,KOTA CIMAHI,83.40,2021,NaN,NaN
322,KOTA TASIKMALAYA,80.52,2021,NaN,NaN
323,KOTA BANJAR,NaN,2019,71.75,NaN
324,KOTA BANJAR,NaN,2020,71.70,NaN

In [43]:
cleaned_dict.keys()

dict_keys(['indeks_pembangunan_manusia_provinsi', 'indeks_kemiskinan_2018', 'indeks_kesehatan_2010', 'persentase_keluhan_2015', 'jumlah_kk_provinsi_jabar'])

In [38]:
# jumlah_kk = pd.read_csv('datasets/umum/15119_jumlah_kepala_keluarga_berdasarkan_golongan_umur_data.csv').copy()
# jumlah_kk['tahun'] = jumlah_kk['tahun'].astype('int64')
# jumlah_kk.drop(columns='Unnamed: 0',inplace=True)
# jumlah_kk = jumlah_kk.groupby(['nama_kabupaten_kota','tahun']).sum().reset_index()

persentase_keluhan = pd.read_csv('datasets/umum/18543_persentase_penduduk_mempunyai_keluhan_kesehatan__kabup_data.csv').copy()
persentase_keluhan['tahun'] = persentase_keluhan['tahun'].astype('int64')
persentase_keluhan.drop(columns='Unnamed: 0',inplace=True)

# persentase_keluhan_kk_2015 = persentase_keluhan.merge(jumlah_kk, how='outer', on=['nama_kabupaten_kota','tahun'])
# persentase_keluhan_kk_2015 = persentase_keluhan_kk_2015.rename(columns={'persentase_penduduk':'persentase_penduduk_'})
# cleaned_dict['persentase_keluhan_kk_2015'] = persentase_keluhan_kk_2015
persentase_keluhan

,nama_kabupaten_kota,persentase_penduduk_mempunyai_keluhan_kesehatan,tahun
0,KABUPATEN BOGOR,35.92,2015
1,KABUPATEN SUKABUMI,30.72,2015
2,KABUPATEN CIANJUR,27.52,2015
3,KABUPATEN BANDUNG,23.61,2015
4,KABUPATEN GARUT,34.23,2015
...,...,...,...
184,KOTA BEKASI,25.46,2021
185,KOTA DEPOK,15.49,2021
186,KOTA CIMAHI,16.23,2021
187,KOTA TASIKMALAYA,18.37,2021
188,KOTA BANJAR,13.71,2021

In [39]:
cleaned_dict['persentase_keluhan_2015'] = persentase_keluhan

In [42]:
jumlah_kk_provinsi_jabar = pd.read_csv('datasets/umum/15119_jumlah_kepala_keluarga_berdasarkan_golongan_umur_data.csv').copy()
jumlah_kk_provinsi_jabar['tahun'] = jumlah_kk_provinsi_jabar['tahun'].astype('int64')
jumlah_kk_provinsi_jabar.drop(columns='Unnamed: 0',inplace=True)
cleaned_dict['jumlah_kk_provinsi_jabar'] = jumlah_kk_provinsi_jabar
jumlah_kk_provinsi_jabar

      umur jenis_kelamin  jumlah_kepala_keluarga  tahun
0    10-14     LAKI-LAKI                     508   2015
1    10-14     PEREMPUAN                     498   2015
2    15-19     LAKI-LAKI                   11211   2015
3    15-19     PEREMPUAN                   15830   2015
4    20-24     LAKI-LAKI                  232243   2015
..     ...           ...                     ...    ...
153  65-69     PEREMPUAN                  300749   2021
154  70-74     LAKI-LAKI                  334583   2021
155  70-74     PEREMPUAN                  222588   2021
156   > 75     LAKI-LAKI                  353266   2021
157   > 75     PEREMPUAN                  314572   2021

[158 rows x 4 columns]

In [ ]:
pathway = 'datasets/hamil/'
ibu_hamil_resti = pd.read_csv(pathway + 'jml_ibu_hamil_mnglm_resiko_tinggi_kehamilan_resti__desa_kel_data.csv').copy()
ibu_hamil_resti.iloc[:,1:] = ibu_hamil_resti.iloc[:,1:].astype('int64')
kunjungan_resti = pd.read_csv(pathway + 'jml_ibu_hamil_mnglm_resiko_tinggi_kehamilan_resti_mendapat__data.csv').copy()
kunjungan_resti.iloc[:,1:] = kunjungan_resti.iloc[:,1:].astype('int64')
ibu_hamil_resti = ibu_hamil_resti.merge(kunjungan_resti, on=['nama_kabupaten_kota','tahun'])
ibu_hamil_resti['kumulatif_resti'] = ibu_hamil_resti.groupby(['nama_kabupaten_kota'])['jumlah_ibu_hamil_resti'].cumsum()
ibu_hamil_resti['kumulatif_kunjungan_resti'] = ibu_hamil_resti.groupby(['nama_kabupaten_kota'])['jumlah_ibu_hamil_resti_kunjungan'].cumsum()
ibu_hamil_resti

In [ ]:
pathway = 'datasets/hamil/'
ibu_hamil_konvergensi = pd.read_csv(pathway + 'jml_ssrn_konvergensi_desa_terhadap_ibu_hamil__desa_keluraha_data.csv').copy()
ibu_hamil_konvergensi.iloc[:,1:] = ibu_hamil_konvergensi.iloc[:,1:].astype('int64')
realisasi_konvergensi = pd.read_csv(pathway + 'jml_realisasi_konvergensi_desa_terhadap_ibu_hamil__desa_kel_data.csv').copy()
realisasi_konvergensi.iloc[:,1:] = realisasi_konvergensi.iloc[:,1:].astype('int64')
ibu_hamil_konvergensi = ibu_hamil_konvergensi.merge(realisasi_konvergensi, on=['nama_kabupaten_kota','tahun'])
# ibu_hamil_konvergensi['kumulatif_resti'] = ibu_hamil_konvergensi.groupby(['nama_kabupaten_kota'])['jumlah_ibu_hamil_resti'].cumsum()
# ibu_hamil_konvergensi['kumulatif_kunjungan_resti'] = ibu_hamil_konvergensi.groupby(['nama_kabupaten_kota'])['jumlah_ibu_hamil_resti_kunjungan'].cumsum()
# ibu_hamil_konvergensi

In [ ]:
ibu_hamil_konvergensi

In [ ]:
pathway = 'datasets/hamil/'
ibu_hamil_anemia = pd.read_csv(pathway + 'jml_ibu_hamil_mengidap_anemia__kabupaten_kota_data.csv').copy()
ibu_hamil_anemia.drop(columns='Unnamed: 0',inplace=True)
ibu_hamil_anemia.iloc[:,1:] = ibu_hamil_anemia.iloc[:,1:].astype('int64')
ibu_hamil_anemia.head()

In [ ]:
pathway = 'datasets/hamil/'
ibu_hamil_konseling_gizi = pd.read_csv(pathway + 'jml_ibu_hamil_mengikuti_konseling_gizi_kelas_ibu_minimal_4__data.csv').copy()
ibu_hamil_konseling_gizi.iloc[:,1:] = ibu_hamil_konseling_gizi.iloc[:,1:].astype('int64')

ibu_hamil_air_minum = pd.read_csv(pathway + 'jml_ibu_hamil_milik_akses_air_minum_aman__desa_kelurahan_data.csv').copy()
ibu_hamil_air_minum.iloc[:,1:] = ibu_hamil_air_minum.iloc[:,1:].astype('int64')
akses_ibu_hamil = ibu_hamil_konseling_gizi.merge(ibu_hamil_air_minum, on=['nama_kabupaten_kota','tahun'])
ibu_hamil_jamban = pd.read_csv(pathway + 'jml_ibu_hamil_milik_jamban_layak__desa_kelurahan_data.csv').copy()
ibu_hamil_jamban.iloc[:,1:] = ibu_hamil_jamban.iloc[:,1:].astype('int64')
akses_ibu_hamil = akses_ibu_hamil.merge(ibu_hamil_jamban, on=['nama_kabupaten_kota','tahun'])
ibu_hamil_jamkes = pd.read_csv(pathway + 'jml_ibu_hamil_milik_jaminan_kshtn__desa_kelurahan_data.csv').copy()
ibu_hamil_jamkes.iloc[:,1:] = ibu_hamil_jamkes.iloc[:,1:].astype('int64')
akses_ibu_hamil = akses_ibu_hamil.merge(ibu_hamil_jamkes, on=['nama_kabupaten_kota','tahun'])
ibu_hamil_periksa = pd.read_csv(pathway + 'jml_ibu_hamil_periksa_4_kali_selama_kehamilan__desa_kelurah_data.csv').copy()
ibu_hamil_periksa.iloc[:,1:] = ibu_hamil_periksa.iloc[:,1:].astype('int64')
akses_ibu_hamil = akses_ibu_hamil.merge(ibu_hamil_periksa, on=['nama_kabupaten_kota','tahun'])

In [ ]:
akses_ibu_hamil = akses_ibu_hamil.merge(ibu_hamil_konvergensi, on=['nama_kabupaten_kota','tahun'])
akses_ibu_hamil.head()

In [ ]:
mortalitas_melahirkan = pd.read_csv(pathway + 'jml_kejadian_kematian_ibu_melahirkan__desa_kelurahan_data.csv').copy()
mortalitas_melahirkan.iloc[:,1:] = mortalitas_melahirkan.iloc[:,1:].astype('int64')
mortalitas_melahirkan.rename(columns={'jumlah_kejadian_kematian_ibu':'jumlah_kejadian_kematian_ibu_melahirkan'})
mortalitas_melahirkan.head()

In [ ]:
pathway = 'datasets/hamil/'
persentase_asi_eksklusif = pd.read_csv(pathway + 'persentase_pemberian_air_susu_ibu_asi_eksklusif_pada_b_data.csv').copy()
persentase_asi_eksklusif.drop(columns='Unnamed: 0',inplace=True)
persentase_asi_eksklusif.tail()

In [ ]:
persentase_persalinan = pd.read_csv(pathway + 'persentase_persalinan_pada_ibu_hamil__kategori_data.csv').copy()
persentase_persalinan.drop(columns='Unnamed: 0',inplace=True)
persentase_persalinan['persentase_persalinan'] = persentase_persalinan['persentase_persalinan'].apply(lambda x:100 if x>100 else x)
persentase_persalinan

In [ ]:

jumlah_ibu_hamil = pd.read_csv(pathway + 'jumlah_ibu_hamil_berdasarkan_kabupatenkota_data.csv').copy()
jumlah_ibu_hamil.drop(columns='Unnamed: 0',inplace=True)
jumlah_ibu_hamil.head()

In [ ]:
kematian_ibu_hamil = pd.read_csv(pathway + 'jumlah_kematian_ibu_hamil_berdasarkan_kelompok_umur_data.csv').copy()
kematian_ibu_hamil.drop(columns='Unnamed: 0',inplace=True)

kematian_ibu_hamil.fillna(0,inplace=True)
kematian_ibu_hamil.iloc[:,2:] = kematian_ibu_hamil.iloc[:,2:].astype('int64')

In [ ]:
cleaned_dict = {}
cleaned_dict.update({'rumah_singgah_ibu_hamil' : rumah_singgah_ibu_hamil,
'ibu_hamil_kek':ibu_hamil_kek,
'ibu_hamil_resti':ibu_hamil_resti,
'ibu_hamil_anemia':ibu_hamil_anemia,
'akses_ibu_hamil':akses_ibu_hamil,
'mortalitas_melahirkan':mortalitas_melahirkan,
'persentase_asi_eksklusif':persentase_asi_eksklusif,
'persentase_persalinan':persentase_persalinan,
'jumlah_ibu_hamil':jumlah_ibu_hamil,
'kematian_ibu_hamil':kematian_ibu_hamil
})

In [ ]:
cleaned_dict.keys()

In [44]:
import os
directory = "cleaned"
parent_dir = "datasets/umum"
path = os.path.join(parent_dir, directory)
os.mkdir(path)
for keys in cleaned_dict:
    cleaned_dict[keys].to_csv(pathway + 'cleaned/' + keys + '.csv',index=False)